name = "insights-worker-dev"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "alleato"
database_id = "fc7c9a6d-ca65-4768-b3f9-07ec5afb38c5"

# AI binding for Cloudflare AI
[ai]
binding = "AI"

# Environment-specific configurations
[env.staging]
name = "insights-worker-staging"

[env.production]
name = "insights-worker"